local Finity = loadstring(game:HttpGet("http://finity.vip/scripts/finity_lib.lua"))()
local FinityWindow = Finity.new(false)
FinityWindow.ChangeToggleKey(Enum.KeyCode.Insert)
local HubCategory = FinityWindow:Category("Hubs")
local ScriptHubButtons = HubCategory:Sector("Hubs")
ScriptHubButtons:Cheat("Button", "Dark Hub", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/yCrBkPaY'), true))()
end)
ScriptHubButtons:Cheat("Button", "Boo Hub", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/PurpleHubs/GhostyHub/master/hubv1.txt'), true))()
end)
ScriptHubButtons:Cheat("Button", "Owl Hub", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt'), true))()
end)
ScriptHubButtons:Cheat("Button", "Rawr Hub", function()
   loadstring(game:HttpGet(('https://pastebinp.com/raw/xDRgGGxd'), true))()
end)
ScriptHubButtons:Cheat("Button", "Zyrex Hub", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Denverrz/scripts/master/Zyrex_Hub.lua'), true))()
end)
local AdminHubButtons = HubCategory:Sector("Admin")
AdminHubButtons:Cheat("Button", "CMD-FE X", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/F3JvpCDM'), true))()
end)
AdminHubButtons:Cheat("Button", "Infinite Yield", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'), true))()
end)
local mostGamesCategory = FinityWindow:Category("most Games")
local GuisCategory = mostGamesCategory:Sector("Guis")
GuisCategory:Cheat("Button", "Lagswitch", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/for_the_most_games/lagswitch_gui.lua'), true))()
end)
GuisCategory:Cheat("Button", "Unachorded Parts", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/for_the_most_games/tp_unachorded_parts_gui.lua'), true))()
end)
local single_most_scripts = mostGamesCategory:Sector("Single Scripts")
single_most_scripts:Cheat("Button", "Anti AFK", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/for_the_most_games/anti_afk.lua'), true))()
end)
single_most_scripts:Cheat("Button", "Chat Bypass", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/for_the_most_games/lightspeed_chat_bypass.lua'), true))()
end)
local graphic_scripts = mostGamesCategory:Sector("Graphical Scripts")
graphic_scripts:Cheat("Button", "lower Graphics(more FPS)", function()
   for i,v in pairs(workspace:GetDescendants()) do
if v:IsA("Part") or v:IsA("MeshPart") or v:IsA("BasePart") then
v.Material = "SmoothPlastic"
end
end
for i,v in pairs(game:GetDescendants()) do
if v:IsA("Light") or v:IsA("ParticleEmitter") or v:IsA("Trail") then
v:Destroy()
end
end
end)
graphic_scripts:Cheat("Button", "Better Graphics", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/for_the_most_games/graphic_enhancer.lua'), true))()
end)
local other_most = mostGamesCategory:Sector("other")
other_most:Cheat("Button", "invis Fling", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/for_the_most_games/invis_fling.lua'), true))()
end)
local single_scripts = FinityWindow:Category("Single Scripts")
local jailbreak = single_scripts:Sector("Jailbreak")
jailbreak:Cheat("Button", "Tesla", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Jailbreak/jailbreak_tesla_gui.lua'), true))()
end)
jailbreak:Cheat("Button", "free Gamepass", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Jailbreak/jailbreak_free_gamepass.lua'), true))()
end)
jailbreak:Cheat("Button", "inf Jetpack Fuel", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Jailbreak/jailbreak_inf_jetpack_fuel.lua'), true))()
end)
local anime_fight_sim = single_scripts:Sector("Anime Fight Simulator")
anime_fight_sim:Cheat("Button", "Autofarm", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/nY2WC60k'), true))()
end)
anime_fight_sim:Cheat("Button", "free Gamepass", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/anime_fight_sim_free_gamepasses.lua'), true))()
end)
anime_fight_sim:Cheat("Button", "Devil Fruit ESP", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/NBQKENww'), true))()
end)
local ragdoll_engine = single_scripts:Sector("Ragdoll Engine")
ragdoll_engine:Cheat("Button", "GUI", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/ragdoll_engine_gui.lua'), true))()
end)
ragdoll_engine:Cheat("Button", "invis all", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/ragdoll_engine_everything_invisible.lua'), true))()
end)
local others_single = single_scripts:Sector("Others")
others_single:Cheat("Button", "Blox Hunt", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/blox_hunt.lua'), true))()
end)
others_single:Cheat("Button", "Obby Maker", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/obby_maker_finish_all_obbys.lua'), true))()
end)
others_single:Cheat("Button", "Project X", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/project_x_gui.lua'), true))()
end)
others_single:Cheat("Button", "Skywars", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/skywars.lua'), true))()
end)
others_single:Cheat("Button", "Blood Samurai", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/blood_samurai_gui.lua'), true))()
end)
https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/Doomspire%20X.lua
