local HubCategory = FinityWindow:Category("Hubs")
local ScriptHubButtons = HubCategory:Sector("Hubs")
ScriptHubButtons:Cheat("Button", "Dark Hub", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/yCrBkPaY'), true))()
end)
ScriptHubButtons:Cheat("Button", "Boo Hub", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/PurpleHubs/GhostyHub/master/hubv1.txt'), true))()
end)
ScriptHubButtons:Cheat("Button", "Owl Hub", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt'), true))()
end)
ScriptHubButtons:Cheat("Button", "Rawr Hub", function()
   loadstring(game:HttpGet(('https://pastebinp.com/raw/xDRgGGxd'), true))()
end)
ScriptHubButtons:Cheat("Button", "Zyrex Hub", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Denverrz/scripts/master/Zyrex_Hub.lua'), true))()
end)
local AdminHubButtons = HubCategory:Sector("Admin")
AdminHubButtons:Cheat("Button", "CMD-FE X", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/F3JvpCDM'), true))()
end)
AdminHubButtons:Cheat("Button", "Infinite Yield", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'), true))()
end)