local single_scripts = FinityWindow:Category("Single Scripts")
local jailbreak = single_scripts:Sector("Jailbreak")
jailbreak:Cheat("Button", "Tesla", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Jailbreak/jailbreak_tesla_gui.lua'), true))()
end)
jailbreak:Cheat("Button", "free Gamepass", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Jailbreak/jailbreak_free_gamepass.lua'), true))()
end)
jailbreak:Cheat("Button", "inf Jetpack Fuel", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Jailbreak/jailbreak_inf_jetpack_fuel.lua'), true))()
end)
local anime_fight_sim = single_scripts:Sector("Anime Fight Simulator")
anime_fight_sim:Cheat("Button", "Autofarm", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/nY2WC60k'), true))()
end)
anime_fight_sim:Cheat("Button", "free Gamepass", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/anime_fight_sim_free_gamepasses.lua'), true))()
end)
anime_fight_sim:Cheat("Button", "Devil Fruit ESP", function()
   loadstring(game:HttpGet(('https://pastebin.com/raw/NBQKENww'), true))()
end)
local ragdoll_engine = single_scripts:Sector("Ragdoll Engine")
ragdoll_engine:Cheat("Button", "GUI", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/ragdoll_engine_gui.lua'), true))()
end)
ragdoll_engine:Cheat("Button", "invis all", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/ragdoll_engine_everything_invisible.lua'), true))()
end)
local others_single = single_scripts:Sector("Others")
others_single:Cheat("Button", "Blox Hunt", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/blox_hunt.lua'), true))()
end)
others_single:Cheat("Button", "Obby Maker", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/obby_maker_finish_all_obbys.lua'), true))()
end)
others_single:Cheat("Button", "Project X", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/project_x_gui.lua'), true))()
end)
others_single:Cheat("Button", "Skywars", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/skywars.lua'), true))()
end)
others_single:Cheat("Button", "Blood Samurai", function()
   loadstring(game:HttpGet(('https://raw.githubusercontent.com/Marethyu9999/local_sided_script_collection_v2/Single_game_scripts/blood_samurai_gui.lua'), true))()
end)